### ISSUE TITLE
Error when opening admin pages - charts not generating

### ISSUE THREAD

**Issue by pagaille** [magicsunday/webtrees-descendants-chart#35]
Hi,

Just tried that module on the latest version of webtrees (php80)

The options are displayed but the chart is not generated (endless spinning thing). When going to web tree's config page, the following error is displayed :

```
Class "MagicSunday\Webtrees\ModuleBase\Module\VersionInformation" not found …/modules_v4/webtrees-descendants-chart/src/Traits/ModuleCustomTrait.php:50
#0 …/app/Http/RequestHandlers/ControlPanel.php(143): MagicSunday\Webtrees\DescendantsChart\Module->customModuleLatestVersion()
#1 [internal function]: Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel::Fisharebest\Webtrees\Http\RequestHandlers\{closure}()
#2 …/vendor/illuminate/collections/Arr.php(717): array_filter()
#3 …/vendor/illuminate/collections/Collection.php(358): Illuminate\Support\Arr::where()
#4 …/app/Http/RequestHandlers/ControlPanel.php(144): Illuminate\Support\Collection->filter()
#5 …/app/Http/Middleware/RequestHandler.php(55): Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel->handle()
#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process()
#7 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle()
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process()
#9 …/app/Module/CheckForNewVersion.php(122): Middleland\Dispatcher->handle()
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process()
#11 …/app/Http/Middleware/AuthAdministrator.php(53): Middleland\Dispatcher->handle()
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthAdministrator->process()
#13 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle()
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process()
#15 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#16 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#17 …/app/Http/Middleware/Router.php(161): Fisharebest\Webtrees\Webtrees::dispatch()
#18 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process()
#19 …/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle()
#20 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process()
#21 …/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle()
#22 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process()
#23 …/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle()
#24 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process()
#25 …/app/Http/Middleware/CheckForNewVersion.php(57): Middleland\Dispatcher->handle()
#26 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process()
#27 …/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle()
#28 …/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}()
#29 …/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction()
#30 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process()
#31 …/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle()
#32 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process()
#33 …/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle()
#34 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process()
#35 …/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle()
#36 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process()
#37 …/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle()
#38 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process()
#39 …/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle()
#40 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process()
#41 …/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle()
#42 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process()
#43 …/app/Http/Middleware/UseDatabase.php(122): Middleland\Dispatcher->handle()
#44 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process()
#45 …/app/Http/Middleware/BadBotBlocker.php(282): Middleland\Dispatcher->handle()
#46 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process()
#47 …/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle()
#48 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process()
#49 …/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle()
#50 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process()
#51 …/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle()
#52 …/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process()
#53 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process()
#54 …/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle()
#55 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process()
#56 …/app/Http/Middleware/BaseUrl.php(73): Middleland\Dispatcher->handle()
#57 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process()
#58 …/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle()
#59 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process()
#60 …/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle()
#61 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process()
#62 …/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle()
#63 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process()
#64 …/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle()
#65 …/app/Webtrees.php(275): Middleland\Dispatcher->dispatch()
#66 …/app/Webtrees.php(262): Fisharebest\Webtrees\Webtrees::dispatch()
#67 …/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest()
#68 {main}
```

what's happening ?

Txs

**Comment by magicsunday** [comment]
What version of the module are you trying to install? Master branch is upcoming webtrees 2.2 and not released yet. Please use one of the release packages https://github.com/magicsunday/webtrees-descendants-chart/releases
